from solo_legged_gym.envs.base.base_task import BaseTask
from solo_legged_gym.envs.base.base_config import BaseEnvCfg, BaseTrainCfg

from solo_legged_gym.envs.solo12_dominic_position.solo12_dominic_position import Solo12DOMINOPosition
from solo_legged_gym.envs.solo12_dominic_position.solo12_dominic_position_config import Solo12DOMINICPositionEnvCfg, Solo12DOMINICPositionTrainCfg


from solo_legged_gym.utils.task_registry import task_registry
task_registry.register("solo12_dominic_position", Solo12DOMINOPosition, Solo12DOMINICPositionEnvCfg(), Solo12DOMINICPositionTrainCfg())
